/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * CodeSage API (dev)
 * OpenAPI spec version: 0.1.0
 */
import { useMutation, useQuery } from "@tanstack/react-query";
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from "@tanstack/react-query";

import * as axios from "axios";
import type { AxiosError, AxiosRequestConfig, AxiosResponse } from "axios";

import type {
  CreateIntegrationBindingRequest,
  CreateProjectRequest,
  GetIntegrationBindingCandidatesParams,
  HTTPValidationError,
  IntegrationBindingCandidatesResponse,
  IntegrationBindingsResponse,
  ProjectResponse,
  StatusResponse,
} from "../../models";

/**
 * Create a new project.
 * @summary Create Project
 */
export const createProject = (
  createProjectRequest: CreateProjectRequest,
  options?: AxiosRequestConfig,
): Promise<AxiosResponse<ProjectResponse>> => {
  return axios.default.post(`/api/projects`, createProjectRequest, options);
};

export const getCreateProjectMutationOptions = <
  TError = AxiosError<StatusResponse | HTTPValidationError>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof createProject>>,
    TError,
    { data: CreateProjectRequest },
    TContext
  >;
  axios?: AxiosRequestConfig;
}): UseMutationOptions<
  Awaited<ReturnType<typeof createProject>>,
  TError,
  { data: CreateProjectRequest },
  TContext
> => {
  const mutationKey = ["createProject"];
  const { mutation: mutationOptions, axios: axiosOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, axios: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof createProject>>,
    { data: CreateProjectRequest }
  > = (props) => {
    const { data } = props ?? {};

    return createProject(data, axiosOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type CreateProjectMutationResult = NonNullable<
  Awaited<ReturnType<typeof createProject>>
>;
export type CreateProjectMutationBody = CreateProjectRequest;
export type CreateProjectMutationError = AxiosError<
  StatusResponse | HTTPValidationError
>;

/**
 * @summary Create Project
 */
export const useCreateProject = <
  TError = AxiosError<StatusResponse | HTTPValidationError>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof createProject>>,
      TError,
      { data: CreateProjectRequest },
      TContext
    >;
    axios?: AxiosRequestConfig;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof createProject>>,
  TError,
  { data: CreateProjectRequest },
  TContext
> => {
  const mutationOptions = getCreateProjectMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * Delete a project.
 * @summary Delete Project
 */
export const deleteProject = (
  projectId: string,
  options?: AxiosRequestConfig,
): Promise<AxiosResponse<StatusResponse>> => {
  return axios.default.delete(`/api/projects/${projectId}`, options);
};

export const getDeleteProjectMutationOptions = <
  TError = AxiosError<StatusResponse | HTTPValidationError>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof deleteProject>>,
    TError,
    { projectId: string },
    TContext
  >;
  axios?: AxiosRequestConfig;
}): UseMutationOptions<
  Awaited<ReturnType<typeof deleteProject>>,
  TError,
  { projectId: string },
  TContext
> => {
  const mutationKey = ["deleteProject"];
  const { mutation: mutationOptions, axios: axiosOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, axios: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof deleteProject>>,
    { projectId: string }
  > = (props) => {
    const { projectId } = props ?? {};

    return deleteProject(projectId, axiosOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type DeleteProjectMutationResult = NonNullable<
  Awaited<ReturnType<typeof deleteProject>>
>;

export type DeleteProjectMutationError = AxiosError<
  StatusResponse | HTTPValidationError
>;

/**
 * @summary Delete Project
 */
export const useDeleteProject = <
  TError = AxiosError<StatusResponse | HTTPValidationError>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof deleteProject>>,
      TError,
      { projectId: string },
      TContext
    >;
    axios?: AxiosRequestConfig;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof deleteProject>>,
  TError,
  { projectId: string },
  TContext
> => {
  const mutationOptions = getDeleteProjectMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * Get a project by its ID.
 * @summary Get Project
 */
export const getProject = (
  projectId: string,
  options?: AxiosRequestConfig,
): Promise<AxiosResponse<ProjectResponse>> => {
  return axios.default.get(`/api/projects/${projectId}`, options);
};

export const getGetProjectQueryKey = (projectId: string) => {
  return [`/api/projects/${projectId}`] as const;
};

export const getGetProjectQueryOptions = <
  TData = Awaited<ReturnType<typeof getProject>>,
  TError = AxiosError<StatusResponse | HTTPValidationError>,
>(
  projectId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getProject>>, TError, TData>
    >;
    axios?: AxiosRequestConfig;
  },
) => {
  const { query: queryOptions, axios: axiosOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetProjectQueryKey(projectId);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getProject>>> = ({
    signal,
  }) => getProject(projectId, { signal, ...axiosOptions });

  return {
    queryKey,
    queryFn,
    enabled: !!projectId,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof getProject>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetProjectQueryResult = NonNullable<
  Awaited<ReturnType<typeof getProject>>
>;
export type GetProjectQueryError = AxiosError<
  StatusResponse | HTTPValidationError
>;

export function useGetProject<
  TData = Awaited<ReturnType<typeof getProject>>,
  TError = AxiosError<StatusResponse | HTTPValidationError>,
>(
  projectId: string,
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getProject>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getProject>>,
          TError,
          Awaited<ReturnType<typeof getProject>>
        >,
        "initialData"
      >;
    axios?: AxiosRequestConfig;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetProject<
  TData = Awaited<ReturnType<typeof getProject>>,
  TError = AxiosError<StatusResponse | HTTPValidationError>,
>(
  projectId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getProject>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getProject>>,
          TError,
          Awaited<ReturnType<typeof getProject>>
        >,
        "initialData"
      >;
    axios?: AxiosRequestConfig;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetProject<
  TData = Awaited<ReturnType<typeof getProject>>,
  TError = AxiosError<StatusResponse | HTTPValidationError>,
>(
  projectId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getProject>>, TError, TData>
    >;
    axios?: AxiosRequestConfig;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Get Project
 */

export function useGetProject<
  TData = Awaited<ReturnType<typeof getProject>>,
  TError = AxiosError<StatusResponse | HTTPValidationError>,
>(
  projectId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getProject>>, TError, TData>
    >;
    axios?: AxiosRequestConfig;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetProjectQueryOptions(projectId, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * Create a new integration binding.
 * @summary Create Integration Binding
 */
export const createIntegrationBinding = (
  projectId: string,
  createIntegrationBindingRequest: CreateIntegrationBindingRequest,
  options?: AxiosRequestConfig,
): Promise<AxiosResponse<IntegrationBindingsResponse>> => {
  return axios.default.post(
    `/api/projects/${projectId}/integration-bindings`,
    createIntegrationBindingRequest,
    options,
  );
};

export const getCreateIntegrationBindingMutationOptions = <
  TError = AxiosError<StatusResponse | HTTPValidationError>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof createIntegrationBinding>>,
    TError,
    { projectId: string; data: CreateIntegrationBindingRequest },
    TContext
  >;
  axios?: AxiosRequestConfig;
}): UseMutationOptions<
  Awaited<ReturnType<typeof createIntegrationBinding>>,
  TError,
  { projectId: string; data: CreateIntegrationBindingRequest },
  TContext
> => {
  const mutationKey = ["createIntegrationBinding"];
  const { mutation: mutationOptions, axios: axiosOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, axios: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof createIntegrationBinding>>,
    { projectId: string; data: CreateIntegrationBindingRequest }
  > = (props) => {
    const { projectId, data } = props ?? {};

    return createIntegrationBinding(projectId, data, axiosOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type CreateIntegrationBindingMutationResult = NonNullable<
  Awaited<ReturnType<typeof createIntegrationBinding>>
>;
export type CreateIntegrationBindingMutationBody =
  CreateIntegrationBindingRequest;
export type CreateIntegrationBindingMutationError = AxiosError<
  StatusResponse | HTTPValidationError
>;

/**
 * @summary Create Integration Binding
 */
export const useCreateIntegrationBinding = <
  TError = AxiosError<StatusResponse | HTTPValidationError>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof createIntegrationBinding>>,
      TError,
      { projectId: string; data: CreateIntegrationBindingRequest },
      TContext
    >;
    axios?: AxiosRequestConfig;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof createIntegrationBinding>>,
  TError,
  { projectId: string; data: CreateIntegrationBindingRequest },
  TContext
> => {
  const mutationOptions = getCreateIntegrationBindingMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * Get all integration bindings for a project.
 * @summary Get Integration Bindings
 */
export const getIntegrationBindings = (
  projectId: string,
  options?: AxiosRequestConfig,
): Promise<AxiosResponse<IntegrationBindingsResponse>> => {
  return axios.default.get(
    `/api/projects/${projectId}/integration-bindings`,
    options,
  );
};

export const getGetIntegrationBindingsQueryKey = (projectId: string) => {
  return [`/api/projects/${projectId}/integration-bindings`] as const;
};

export const getGetIntegrationBindingsQueryOptions = <
  TData = Awaited<ReturnType<typeof getIntegrationBindings>>,
  TError = AxiosError<StatusResponse | HTTPValidationError>,
>(
  projectId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getIntegrationBindings>>,
        TError,
        TData
      >
    >;
    axios?: AxiosRequestConfig;
  },
) => {
  const { query: queryOptions, axios: axiosOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getGetIntegrationBindingsQueryKey(projectId);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getIntegrationBindings>>
  > = ({ signal }) =>
    getIntegrationBindings(projectId, { signal, ...axiosOptions });

  return {
    queryKey,
    queryFn,
    enabled: !!projectId,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof getIntegrationBindings>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetIntegrationBindingsQueryResult = NonNullable<
  Awaited<ReturnType<typeof getIntegrationBindings>>
>;
export type GetIntegrationBindingsQueryError = AxiosError<
  StatusResponse | HTTPValidationError
>;

export function useGetIntegrationBindings<
  TData = Awaited<ReturnType<typeof getIntegrationBindings>>,
  TError = AxiosError<StatusResponse | HTTPValidationError>,
>(
  projectId: string,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getIntegrationBindings>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getIntegrationBindings>>,
          TError,
          Awaited<ReturnType<typeof getIntegrationBindings>>
        >,
        "initialData"
      >;
    axios?: AxiosRequestConfig;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetIntegrationBindings<
  TData = Awaited<ReturnType<typeof getIntegrationBindings>>,
  TError = AxiosError<StatusResponse | HTTPValidationError>,
>(
  projectId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getIntegrationBindings>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getIntegrationBindings>>,
          TError,
          Awaited<ReturnType<typeof getIntegrationBindings>>
        >,
        "initialData"
      >;
    axios?: AxiosRequestConfig;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetIntegrationBindings<
  TData = Awaited<ReturnType<typeof getIntegrationBindings>>,
  TError = AxiosError<StatusResponse | HTTPValidationError>,
>(
  projectId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getIntegrationBindings>>,
        TError,
        TData
      >
    >;
    axios?: AxiosRequestConfig;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Get Integration Bindings
 */

export function useGetIntegrationBindings<
  TData = Awaited<ReturnType<typeof getIntegrationBindings>>,
  TError = AxiosError<StatusResponse | HTTPValidationError>,
>(
  projectId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getIntegrationBindings>>,
        TError,
        TData
      >
    >;
    axios?: AxiosRequestConfig;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetIntegrationBindingsQueryOptions(
    projectId,
    options,
  );

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * Get all integration binding candidates for a project.
 * @summary Get Integration Binding Candidates
 */
export const getIntegrationBindingCandidates = (
  projectId: string,
  params: GetIntegrationBindingCandidatesParams,
  options?: AxiosRequestConfig,
): Promise<AxiosResponse<IntegrationBindingCandidatesResponse>> => {
  return axios.default.get(`/api/projects/${projectId}/binding-candidates`, {
    ...options,
    params: { ...params, ...options?.params },
  });
};

export const getGetIntegrationBindingCandidatesQueryKey = (
  projectId: string,
  params: GetIntegrationBindingCandidatesParams,
) => {
  return [
    `/api/projects/${projectId}/binding-candidates`,
    ...(params ? [params] : []),
  ] as const;
};

export const getGetIntegrationBindingCandidatesQueryOptions = <
  TData = Awaited<ReturnType<typeof getIntegrationBindingCandidates>>,
  TError = AxiosError<StatusResponse | HTTPValidationError>,
>(
  projectId: string,
  params: GetIntegrationBindingCandidatesParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getIntegrationBindingCandidates>>,
        TError,
        TData
      >
    >;
    axios?: AxiosRequestConfig;
  },
) => {
  const { query: queryOptions, axios: axiosOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ??
    getGetIntegrationBindingCandidatesQueryKey(projectId, params);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof getIntegrationBindingCandidates>>
  > = ({ signal }) =>
    getIntegrationBindingCandidates(projectId, params, {
      signal,
      ...axiosOptions,
    });

  return {
    queryKey,
    queryFn,
    enabled: !!projectId,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof getIntegrationBindingCandidates>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetIntegrationBindingCandidatesQueryResult = NonNullable<
  Awaited<ReturnType<typeof getIntegrationBindingCandidates>>
>;
export type GetIntegrationBindingCandidatesQueryError = AxiosError<
  StatusResponse | HTTPValidationError
>;

export function useGetIntegrationBindingCandidates<
  TData = Awaited<ReturnType<typeof getIntegrationBindingCandidates>>,
  TError = AxiosError<StatusResponse | HTTPValidationError>,
>(
  projectId: string,
  params: GetIntegrationBindingCandidatesParams,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getIntegrationBindingCandidates>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getIntegrationBindingCandidates>>,
          TError,
          Awaited<ReturnType<typeof getIntegrationBindingCandidates>>
        >,
        "initialData"
      >;
    axios?: AxiosRequestConfig;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetIntegrationBindingCandidates<
  TData = Awaited<ReturnType<typeof getIntegrationBindingCandidates>>,
  TError = AxiosError<StatusResponse | HTTPValidationError>,
>(
  projectId: string,
  params: GetIntegrationBindingCandidatesParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getIntegrationBindingCandidates>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getIntegrationBindingCandidates>>,
          TError,
          Awaited<ReturnType<typeof getIntegrationBindingCandidates>>
        >,
        "initialData"
      >;
    axios?: AxiosRequestConfig;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetIntegrationBindingCandidates<
  TData = Awaited<ReturnType<typeof getIntegrationBindingCandidates>>,
  TError = AxiosError<StatusResponse | HTTPValidationError>,
>(
  projectId: string,
  params: GetIntegrationBindingCandidatesParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getIntegrationBindingCandidates>>,
        TError,
        TData
      >
    >;
    axios?: AxiosRequestConfig;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Get Integration Binding Candidates
 */

export function useGetIntegrationBindingCandidates<
  TData = Awaited<ReturnType<typeof getIntegrationBindingCandidates>>,
  TError = AxiosError<StatusResponse | HTTPValidationError>,
>(
  projectId: string,
  params: GetIntegrationBindingCandidatesParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getIntegrationBindingCandidates>>,
        TError,
        TData
      >
    >;
    axios?: AxiosRequestConfig;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetIntegrationBindingCandidatesQueryOptions(
    projectId,
    params,
    options,
  );

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}
