/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * CodeSage API (dev)
 * OpenAPI spec version: 0.1.0
 */
import { useMutation } from "@tanstack/react-query";
import type {
  MutationFunction,
  QueryClient,
  UseMutationOptions,
  UseMutationResult,
} from "@tanstack/react-query";

import * as axios from "axios";
import type { AxiosError, AxiosRequestConfig, AxiosResponse } from "axios";

import type {
  BaseErrorResponse,
  ChatCreateRequest,
  HTTPValidationError,
  StatusResponse,
} from "../../models";

/**
 * Create a new chat for a project.
 * @summary Create Chat
 */
export const createChat = (
  projectId: string,
  chatCreateRequest: ChatCreateRequest,
  options?: AxiosRequestConfig,
): Promise<AxiosResponse<StatusResponse>> => {
  return axios.default.post(
    `/api/projects/${projectId}/chats`,
    chatCreateRequest,
    options,
  );
};

export const getCreateChatMutationOptions = <
  TError = AxiosError<BaseErrorResponse | HTTPValidationError>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof createChat>>,
    TError,
    { projectId: string; data: ChatCreateRequest },
    TContext
  >;
  axios?: AxiosRequestConfig;
}): UseMutationOptions<
  Awaited<ReturnType<typeof createChat>>,
  TError,
  { projectId: string; data: ChatCreateRequest },
  TContext
> => {
  const mutationKey = ["createChat"];
  const { mutation: mutationOptions, axios: axiosOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, axios: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof createChat>>,
    { projectId: string; data: ChatCreateRequest }
  > = (props) => {
    const { projectId, data } = props ?? {};

    return createChat(projectId, data, axiosOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type CreateChatMutationResult = NonNullable<
  Awaited<ReturnType<typeof createChat>>
>;
export type CreateChatMutationBody = ChatCreateRequest;
export type CreateChatMutationError = AxiosError<
  BaseErrorResponse | HTTPValidationError
>;

/**
 * @summary Create Chat
 */
export const useCreateChat = <
  TError = AxiosError<BaseErrorResponse | HTTPValidationError>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof createChat>>,
      TError,
      { projectId: string; data: ChatCreateRequest },
      TContext
    >;
    axios?: AxiosRequestConfig;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof createChat>>,
  TError,
  { projectId: string; data: ChatCreateRequest },
  TContext
> => {
  const mutationOptions = getCreateChatMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
