/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * CodeSage API (dev)
 * OpenAPI spec version: 0.1.0
 */
import { useMutation, useQuery } from "@tanstack/react-query";
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from "@tanstack/react-query";

import * as axios from "axios";
import type { AxiosError, AxiosRequestConfig, AxiosResponse } from "axios";

import type {
  HTTPValidationError,
  InterruptResolutionRequest,
  ProjectTaskRequest,
  StatusResponse,
  TaskResponse,
  TasksResponse,
} from "../../models";

/**
 * Create a new task for a project.
 * @summary Create Task
 */
export const createTask = (
  projectId: string,
  projectTaskRequest: ProjectTaskRequest,
  options?: AxiosRequestConfig
): Promise<AxiosResponse<TaskResponse>> => {
  return axios.default.post(
    `/api/projects/${projectId}/tasks`,
    projectTaskRequest,
    options
  );
};

export const getCreateTaskMutationOptions = <
  TError = AxiosError<HTTPValidationError>,
  TContext = unknown
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof createTask>>,
    TError,
    { projectId: string; data: ProjectTaskRequest },
    TContext
  >;
  axios?: AxiosRequestConfig;
}): UseMutationOptions<
  Awaited<ReturnType<typeof createTask>>,
  TError,
  { projectId: string; data: ProjectTaskRequest },
  TContext
> => {
  const mutationKey = ["createTask"];
  const { mutation: mutationOptions, axios: axiosOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, axios: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof createTask>>,
    { projectId: string; data: ProjectTaskRequest }
  > = (props) => {
    const { projectId, data } = props ?? {};

    return createTask(projectId, data, axiosOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type CreateTaskMutationResult = NonNullable<
  Awaited<ReturnType<typeof createTask>>
>;
export type CreateTaskMutationBody = ProjectTaskRequest;
export type CreateTaskMutationError = AxiosError<HTTPValidationError>;

/**
 * @summary Create Task
 */
export const useCreateTask = <
  TError = AxiosError<HTTPValidationError>,
  TContext = unknown
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof createTask>>,
      TError,
      { projectId: string; data: ProjectTaskRequest },
      TContext
    >;
    axios?: AxiosRequestConfig;
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof createTask>>,
  TError,
  { projectId: string; data: ProjectTaskRequest },
  TContext
> => {
  const mutationOptions = getCreateTaskMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * Get tasks for a project.
 * @summary Get Tasks
 */
export const getTasks = (
  projectId: string,
  options?: AxiosRequestConfig
): Promise<AxiosResponse<TasksResponse>> => {
  return axios.default.get(`/api/projects/${projectId}/tasks`, options);
};

export const getGetTasksQueryKey = (projectId: string) => {
  return [`/api/projects/${projectId}/tasks`] as const;
};

export const getGetTasksQueryOptions = <
  TData = Awaited<ReturnType<typeof getTasks>>,
  TError = AxiosError<HTTPValidationError>
>(
  projectId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getTasks>>, TError, TData>
    >;
    axios?: AxiosRequestConfig;
  }
) => {
  const { query: queryOptions, axios: axiosOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetTasksQueryKey(projectId);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getTasks>>> = ({
    signal,
  }) => getTasks(projectId, { signal, ...axiosOptions });

  return {
    queryKey,
    queryFn,
    enabled: !!projectId,
    ...queryOptions,
  } as UseQueryOptions<Awaited<ReturnType<typeof getTasks>>, TError, TData> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };
};

export type GetTasksQueryResult = NonNullable<
  Awaited<ReturnType<typeof getTasks>>
>;
export type GetTasksQueryError = AxiosError<HTTPValidationError>;

export function useGetTasks<
  TData = Awaited<ReturnType<typeof getTasks>>,
  TError = AxiosError<HTTPValidationError>
>(
  projectId: string,
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getTasks>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getTasks>>,
          TError,
          Awaited<ReturnType<typeof getTasks>>
        >,
        "initialData"
      >;
    axios?: AxiosRequestConfig;
  },
  queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetTasks<
  TData = Awaited<ReturnType<typeof getTasks>>,
  TError = AxiosError<HTTPValidationError>
>(
  projectId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getTasks>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getTasks>>,
          TError,
          Awaited<ReturnType<typeof getTasks>>
        >,
        "initialData"
      >;
    axios?: AxiosRequestConfig;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetTasks<
  TData = Awaited<ReturnType<typeof getTasks>>,
  TError = AxiosError<HTTPValidationError>
>(
  projectId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getTasks>>, TError, TData>
    >;
    axios?: AxiosRequestConfig;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Get Tasks
 */

export function useGetTasks<
  TData = Awaited<ReturnType<typeof getTasks>>,
  TError = AxiosError<HTTPValidationError>
>(
  projectId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getTasks>>, TError, TData>
    >;
    axios?: AxiosRequestConfig;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetTasksQueryOptions(projectId, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * Get a task for a project.
 * @summary Get Task
 */
export const getTask = (
  projectId: string,
  taskId: string,
  options?: AxiosRequestConfig
): Promise<AxiosResponse<TaskResponse>> => {
  return axios.default.get(
    `/api/projects/${projectId}/tasks/${taskId}`,
    options
  );
};

export const getGetTaskQueryKey = (projectId: string, taskId: string) => {
  return [`/api/projects/${projectId}/tasks/${taskId}`] as const;
};

export const getGetTaskQueryOptions = <
  TData = Awaited<ReturnType<typeof getTask>>,
  TError = AxiosError<HTTPValidationError>
>(
  projectId: string,
  taskId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getTask>>, TError, TData>
    >;
    axios?: AxiosRequestConfig;
  }
) => {
  const { query: queryOptions, axios: axiosOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getGetTaskQueryKey(projectId, taskId);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getTask>>> = ({
    signal,
  }) => getTask(projectId, taskId, { signal, ...axiosOptions });

  return {
    queryKey,
    queryFn,
    enabled: !!(projectId && taskId),
    ...queryOptions,
  } as UseQueryOptions<Awaited<ReturnType<typeof getTask>>, TError, TData> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };
};

export type GetTaskQueryResult = NonNullable<
  Awaited<ReturnType<typeof getTask>>
>;
export type GetTaskQueryError = AxiosError<HTTPValidationError>;

export function useGetTask<
  TData = Awaited<ReturnType<typeof getTask>>,
  TError = AxiosError<HTTPValidationError>
>(
  projectId: string,
  taskId: string,
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getTask>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getTask>>,
          TError,
          Awaited<ReturnType<typeof getTask>>
        >,
        "initialData"
      >;
    axios?: AxiosRequestConfig;
  },
  queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetTask<
  TData = Awaited<ReturnType<typeof getTask>>,
  TError = AxiosError<HTTPValidationError>
>(
  projectId: string,
  taskId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getTask>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getTask>>,
          TError,
          Awaited<ReturnType<typeof getTask>>
        >,
        "initialData"
      >;
    axios?: AxiosRequestConfig;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetTask<
  TData = Awaited<ReturnType<typeof getTask>>,
  TError = AxiosError<HTTPValidationError>
>(
  projectId: string,
  taskId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getTask>>, TError, TData>
    >;
    axios?: AxiosRequestConfig;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Get Task
 */

export function useGetTask<
  TData = Awaited<ReturnType<typeof getTask>>,
  TError = AxiosError<HTTPValidationError>
>(
  projectId: string,
  taskId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getTask>>, TError, TData>
    >;
    axios?: AxiosRequestConfig;
  },
  queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetTaskQueryOptions(projectId, taskId, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * Update a task for a project.
 * @summary Update Task
 */
export const updateTask = (
  projectId: string,
  taskId: string,
  interruptResolutionRequest: InterruptResolutionRequest,
  options?: AxiosRequestConfig
): Promise<AxiosResponse<StatusResponse>> => {
  return axios.default.patch(
    `/api/projects/${projectId}/tasks/${taskId}`,
    interruptResolutionRequest,
    options
  );
};

export const getUpdateTaskMutationOptions = <
  TError = AxiosError<HTTPValidationError>,
  TContext = unknown
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof updateTask>>,
    TError,
    { projectId: string; taskId: string; data: InterruptResolutionRequest },
    TContext
  >;
  axios?: AxiosRequestConfig;
}): UseMutationOptions<
  Awaited<ReturnType<typeof updateTask>>,
  TError,
  { projectId: string; taskId: string; data: InterruptResolutionRequest },
  TContext
> => {
  const mutationKey = ["updateTask"];
  const { mutation: mutationOptions, axios: axiosOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, axios: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof updateTask>>,
    { projectId: string; taskId: string; data: InterruptResolutionRequest }
  > = (props) => {
    const { projectId, taskId, data } = props ?? {};

    return updateTask(projectId, taskId, data, axiosOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type UpdateTaskMutationResult = NonNullable<
  Awaited<ReturnType<typeof updateTask>>
>;
export type UpdateTaskMutationBody = InterruptResolutionRequest;
export type UpdateTaskMutationError = AxiosError<HTTPValidationError>;

/**
 * @summary Update Task
 */
export const useUpdateTask = <
  TError = AxiosError<HTTPValidationError>,
  TContext = unknown
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof updateTask>>,
      TError,
      { projectId: string; taskId: string; data: InterruptResolutionRequest },
      TContext
    >;
    axios?: AxiosRequestConfig;
  },
  queryClient?: QueryClient
): UseMutationResult<
  Awaited<ReturnType<typeof updateTask>>,
  TError,
  { projectId: string; taskId: string; data: InterruptResolutionRequest },
  TContext
> => {
  const mutationOptions = getUpdateTaskMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
