/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * CodeSage API (dev)
 * OpenAPI spec version: 0.1.0
 */
import { useMutation, useQuery } from "@tanstack/react-query";
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from "@tanstack/react-query";

import * as axios from "axios";
import type { AxiosError, AxiosRequestConfig, AxiosResponse } from "axios";

import type {
  BaseErrorResponse,
  HTTPValidationError,
  IntegrationCreateRequest,
  IntegrationResponse,
} from "../../models";

/**
 * Create a new integration.
 * @summary Create Integration
 */
export const createIntegration = (
  integrationCreateRequest: IntegrationCreateRequest,
  options?: AxiosRequestConfig,
): Promise<AxiosResponse<IntegrationResponse>> => {
  return axios.default.post(
    `/api/integrations`,
    integrationCreateRequest,
    options,
  );
};

export const getCreateIntegrationMutationOptions = <
  TError = AxiosError<BaseErrorResponse | HTTPValidationError>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof createIntegration>>,
    TError,
    { data: IntegrationCreateRequest },
    TContext
  >;
  axios?: AxiosRequestConfig;
}): UseMutationOptions<
  Awaited<ReturnType<typeof createIntegration>>,
  TError,
  { data: IntegrationCreateRequest },
  TContext
> => {
  const mutationKey = ["createIntegration"];
  const { mutation: mutationOptions, axios: axiosOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, axios: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof createIntegration>>,
    { data: IntegrationCreateRequest }
  > = (props) => {
    const { data } = props ?? {};

    return createIntegration(data, axiosOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type CreateIntegrationMutationResult = NonNullable<
  Awaited<ReturnType<typeof createIntegration>>
>;
export type CreateIntegrationMutationBody = IntegrationCreateRequest;
export type CreateIntegrationMutationError = AxiosError<
  BaseErrorResponse | HTTPValidationError
>;

/**
 * @summary Create Integration
 */
export const useCreateIntegration = <
  TError = AxiosError<BaseErrorResponse | HTTPValidationError>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof createIntegration>>,
      TError,
      { data: IntegrationCreateRequest },
      TContext
    >;
    axios?: AxiosRequestConfig;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof createIntegration>>,
  TError,
  { data: IntegrationCreateRequest },
  TContext
> => {
  const mutationOptions = getCreateIntegrationMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * Get an integration by its ID.
 * @summary Get Integration
 */
export const getIntegration = (
  integrationId: string,
  options?: AxiosRequestConfig,
): Promise<AxiosResponse<IntegrationResponse>> => {
  return axios.default.get(`/api/integrations/${integrationId}`, options);
};

export const getGetIntegrationQueryKey = (integrationId: string) => {
  return [`/api/integrations/${integrationId}`] as const;
};

export const getGetIntegrationQueryOptions = <
  TData = Awaited<ReturnType<typeof getIntegration>>,
  TError = AxiosError<BaseErrorResponse | HTTPValidationError>,
>(
  integrationId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getIntegration>>, TError, TData>
    >;
    axios?: AxiosRequestConfig;
  },
) => {
  const { query: queryOptions, axios: axiosOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getGetIntegrationQueryKey(integrationId);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getIntegration>>> = ({
    signal,
  }) => getIntegration(integrationId, { signal, ...axiosOptions });

  return {
    queryKey,
    queryFn,
    enabled: !!integrationId,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof getIntegration>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetIntegrationQueryResult = NonNullable<
  Awaited<ReturnType<typeof getIntegration>>
>;
export type GetIntegrationQueryError = AxiosError<
  BaseErrorResponse | HTTPValidationError
>;

export function useGetIntegration<
  TData = Awaited<ReturnType<typeof getIntegration>>,
  TError = AxiosError<BaseErrorResponse | HTTPValidationError>,
>(
  integrationId: string,
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getIntegration>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getIntegration>>,
          TError,
          Awaited<ReturnType<typeof getIntegration>>
        >,
        "initialData"
      >;
    axios?: AxiosRequestConfig;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetIntegration<
  TData = Awaited<ReturnType<typeof getIntegration>>,
  TError = AxiosError<BaseErrorResponse | HTTPValidationError>,
>(
  integrationId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getIntegration>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getIntegration>>,
          TError,
          Awaited<ReturnType<typeof getIntegration>>
        >,
        "initialData"
      >;
    axios?: AxiosRequestConfig;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetIntegration<
  TData = Awaited<ReturnType<typeof getIntegration>>,
  TError = AxiosError<BaseErrorResponse | HTTPValidationError>,
>(
  integrationId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getIntegration>>, TError, TData>
    >;
    axios?: AxiosRequestConfig;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Get Integration
 */

export function useGetIntegration<
  TData = Awaited<ReturnType<typeof getIntegration>>,
  TError = AxiosError<BaseErrorResponse | HTTPValidationError>,
>(
  integrationId: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getIntegration>>, TError, TData>
    >;
    axios?: AxiosRequestConfig;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetIntegrationQueryOptions(integrationId, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * Delete an integration.
 * @summary Delete Integration
 */
export const deleteIntegration = (
  integrationId: string,
  options?: AxiosRequestConfig,
): Promise<AxiosResponse<IntegrationResponse>> => {
  return axios.default.delete(`/api/integrations/${integrationId}`, options);
};

export const getDeleteIntegrationMutationOptions = <
  TError = AxiosError<BaseErrorResponse | HTTPValidationError>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof deleteIntegration>>,
    TError,
    { integrationId: string },
    TContext
  >;
  axios?: AxiosRequestConfig;
}): UseMutationOptions<
  Awaited<ReturnType<typeof deleteIntegration>>,
  TError,
  { integrationId: string },
  TContext
> => {
  const mutationKey = ["deleteIntegration"];
  const { mutation: mutationOptions, axios: axiosOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, axios: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof deleteIntegration>>,
    { integrationId: string }
  > = (props) => {
    const { integrationId } = props ?? {};

    return deleteIntegration(integrationId, axiosOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type DeleteIntegrationMutationResult = NonNullable<
  Awaited<ReturnType<typeof deleteIntegration>>
>;

export type DeleteIntegrationMutationError = AxiosError<
  BaseErrorResponse | HTTPValidationError
>;

/**
 * @summary Delete Integration
 */
export const useDeleteIntegration = <
  TError = AxiosError<BaseErrorResponse | HTTPValidationError>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof deleteIntegration>>,
      TError,
      { integrationId: string },
      TContext
    >;
    axios?: AxiosRequestConfig;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof deleteIntegration>>,
  TError,
  { integrationId: string },
  TContext
> => {
  const mutationOptions = getDeleteIntegrationMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
