/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * CodeSage API (dev)
 * OpenAPI spec version: 0.1.0
 */
import type { BaseMessageContent } from "./baseMessageContent";
import type { BaseMessageAdditionalKwargs } from "./baseMessageAdditionalKwargs";
import type { BaseMessageResponseMetadata } from "./baseMessageResponseMetadata";
import type { BaseMessageName } from "./baseMessageName";
import type { BaseMessageId } from "./baseMessageId";

/**
 * Base abstract message class.

Messages are the inputs and outputs of ChatModels.
 */
export interface BaseMessage {
  content: BaseMessageContent;
  additional_kwargs?: BaseMessageAdditionalKwargs;
  response_metadata?: BaseMessageResponseMetadata;
  type: string;
  name?: BaseMessageName;
  id?: BaseMessageId;
  [key: string]: unknown;
}
