/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * CodeSage API (dev)
 * OpenAPI spec version: 0.1.0
 */
import type { IntegrationProtocol } from "./integrationProtocol";
import type { IntegrationProviders } from "./integrationProviders";

export interface BindingCandidateSchema {
  /** Integration binding protocol */
  protocol: IntegrationProtocol;
  /** Integration binding remote ID */
  remote_id: string;
  /** Integration binding provider */
  provider: IntegrationProviders;
}
