/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * CodeSage API (dev)
 * OpenAPI spec version: 0.1.0
 */
import type { BodyLoginApiTokenPostGrantType } from "./bodyLoginApiTokenPostGrantType";
import type { BodyLoginApiTokenPostRefreshToken } from "./bodyLoginApiTokenPostRefreshToken";
import type { BodyLoginApiTokenPostUsername } from "./bodyLoginApiTokenPostUsername";
import type { BodyLoginApiTokenPostPassword } from "./bodyLoginApiTokenPostPassword";
import type { BodyLoginApiTokenPostClientId } from "./bodyLoginApiTokenPostClientId";
import type { BodyLoginApiTokenPostClientSecret } from "./bodyLoginApiTokenPostClientSecret";

export interface BodyLoginApiTokenPost {
  grant_type?: BodyLoginApiTokenPostGrantType;
  refresh_token?: BodyLoginApiTokenPostRefreshToken;
  username?: BodyLoginApiTokenPostUsername;
  password?: BodyLoginApiTokenPostPassword;
  scope?: string;
  client_id?: BodyLoginApiTokenPostClientId;
  client_secret?: BodyLoginApiTokenPostClientSecret;
}
