/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * CodeSage API (dev)
 * OpenAPI spec version: 0.1.0
 */
import type { CommitSchema } from "./commitSchema";

export interface BranchSchema {
  id: string;
  name: string;
  head_commit_sha: string;
  commits: CommitSchema[];
}
