/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * CodeSage API (dev)
 * OpenAPI spec version: 0.1.0
 */
import type { GitActorSchema } from "./gitActorSchema";

export interface CommitSchema {
  sha: string;
  message: string;
  author: GitActorSchema;
  committer: GitActorSchema;
  authored_at: string;
  committed_at: string;
  parent_shas?: string[];
}
