/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * CodeSage API (dev)
 * OpenAPI spec version: 0.1.0
 */
import type { ProtocolBindingSchema } from "./protocolBindingSchema";

export interface CreateIntegrationBindingRequest {
  /** List of integration bindings */
  bindings: ProtocolBindingSchema[];
}
