/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * CodeSage API (dev)
 * OpenAPI spec version: 0.1.0
 */
import type { DependencyVersion } from "./dependencyVersion";

export interface Dependency {
  /** Library or framework name. */
  name: string;
  /** Library or framework version */
  version: DependencyVersion;
}
