/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * CodeSage API (dev)
 * OpenAPI spec version: 0.1.0
 */
import type { EnvironmentSetupResultManager } from "./environmentSetupResultManager";
import type { EnvironmentSetupResultEnvironmentPath } from "./environmentSetupResultEnvironmentPath";

export interface EnvironmentSetupResult {
  /** Package manager used to install the dependencies. */
  manager?: EnvironmentSetupResultManager;
  /** Path to the (virtual) environment. Example: .venv, venv */
  environment_path?: EnvironmentSetupResultEnvironmentPath;
}
