/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * CodeSage API (dev)
 * OpenAPI spec version: 0.1.0
 */

/**
 * Path to the (virtual) environment. Example: .venv, venv
 */
export type EnvironmentSetupResultEnvironmentPath = string | null;
