/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * CodeSage API (dev)
 * OpenAPI spec version: 0.1.0
 */
import type { GitActorSchemaName } from "./gitActorSchemaName";
import type { GitActorSchemaEmail } from "./gitActorSchemaEmail";

export interface GitActorSchema {
  name?: GitActorSchemaName;
  email?: GitActorSchemaEmail;
}
