/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * CodeSage API (dev)
 * OpenAPI spec version: 0.1.0
 */
import type { InitialScanSupervisorResultSubpath } from "./initialScanSupervisorResultSubpath";
import type { RepoScannerResult } from "./repoScannerResult";
import type { ToolAnalysisResult } from "./toolAnalysisResult";

export interface InitialScanSupervisorResult {
  /** Repository subpath that the result is about. Used if there are multiple projects in the same repository. */
  subpath: InitialScanSupervisorResultSubpath;
  /** RepoScannerAgent result for the current subpath or the whole repository if no subprojects were detected. */
  scanner_result: RepoScannerResult;
  /** ToolAnalysisAgent result for the current subpath or the whole repository if no subprojects were detected. */
  tool_analysis_result: ToolAnalysisResult;
}
