/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * CodeSage API (dev)
 * OpenAPI spec version: 0.1.0
 */
import type { GitLabIntegrationConfigInput } from "./gitLabIntegrationConfigInput";
import type { SecretRequestSchema } from "./secretRequestSchema";
import type { OwnerRequestSchema } from "./ownerRequestSchema";

export interface IntegrationCreateGitLabSchema {
  /** Integration name */
  name: string;
  /** Provider type (gitlab) */
  provider?: "gitlab";
  /** GitLab integration configuration */
  config: GitLabIntegrationConfigInput;
  /** Integration credentials */
  secret: SecretRequestSchema;
  /** Integration owner */
  owner: OwnerRequestSchema;
}
