/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * CodeSage API (dev)
 * OpenAPI spec version: 0.1.0
 */
import type { IntegrationGithubSchema } from "./integrationGithubSchema";
import type { IntegrationGitlabSchema } from "./integrationGitlabSchema";
import type { IntegrationSentrySchema } from "./integrationSentrySchema";

export type IntegrationsResponseIntegrationsItem =
  | IntegrationGithubSchema
  | IntegrationGitlabSchema
  | IntegrationSentrySchema;
