/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * CodeSage API (dev)
 * OpenAPI spec version: 0.1.0
 */

export type IntegrationProviders =
  (typeof IntegrationProviders)[keyof typeof IntegrationProviders];

export const IntegrationProviders = {
  github: "github",
  gitlab: "gitlab",
  sentry: "sentry",
} as const;
