/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * CodeSage API (dev)
 * OpenAPI spec version: 0.1.0
 */
import type { GitLabIntegrationConfigOutput } from "./gitLabIntegrationConfigOutput";
import type { IntegrationGitlabSchemaOwner } from "./integrationGitlabSchemaOwner";
import type { SecretResponseSchema } from "./secretResponseSchema";

export interface IntegrationGitlabSchema {
  created_at: string;
  updated_at: string;
  /** Integration ID */
  id: string;
  /** Integration name */
  name: string;
  /** Provider type (gitlab) */
  provider?: "gitlab";
  /** GitLab integration configuration */
  config: GitLabIntegrationConfigOutput;
  /** Integration owner */
  owner?: IntegrationGitlabSchemaOwner;
  /** Integration credentials (without value) */
  secret: SecretResponseSchema;
}
