/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * CodeSage API (dev)
 * OpenAPI spec version: 0.1.0
 */

export type IntegrationProtocol =
  (typeof IntegrationProtocol)[keyof typeof IntegrationProtocol];

export const IntegrationProtocol = {
  repository: "repository",
  ci: "ci",
  error_monitoring: "error_monitoring",
} as const;
