/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * CodeSage API (dev)
 * OpenAPI spec version: 0.1.0
 */
import type { IntegrationCreateGitHubSchema } from "./integrationCreateGitHubSchema";
import type { IntegrationCreateGitLabSchema } from "./integrationCreateGitLabSchema";
import type { IntegrationCreateSentrySchema } from "./integrationCreateSentrySchema";

/**
 * Integration creation data
 */
export type IntegrationCreateRequestIntegration =
  | IntegrationCreateGitHubSchema
  | IntegrationCreateGitLabSchema
  | IntegrationCreateSentrySchema;
