/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * CodeSage API (dev)
 * OpenAPI spec version: 0.1.0
 */
import type { SentryIntegrationConfig } from "./sentryIntegrationConfig";
import type { SecretRequestSchema } from "./secretRequestSchema";
import type { OwnerRequestSchema } from "./ownerRequestSchema";

export interface IntegrationCreateSentrySchema {
  /** Integration name */
  name: string;
  /** Provider type (sentry) */
  provider?: "sentry";
  /** Sentry integration configuration */
  config: SentryIntegrationConfig;
  /** Integration credentials */
  secret: SecretRequestSchema;
  /** Integration owner */
  owner: OwnerRequestSchema;
}
