/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * CodeSage API (dev)
 * OpenAPI spec version: 0.1.0
 */
import type { GitHubIntegrationConfigOutput } from "./gitHubIntegrationConfigOutput";
import type { IntegrationGithubSchemaOwner } from "./integrationGithubSchemaOwner";
import type { SecretResponseSchema } from "./secretResponseSchema";

export interface IntegrationGithubSchema {
  created_at: string;
  updated_at: string;
  /** Integration ID */
  id: string;
  /** Integration name */
  name: string;
  /** Provider type (github) */
  provider?: "github";
  /** GitHub integration configuration */
  config: GitHubIntegrationConfigOutput;
  /** Integration owner */
  owner?: IntegrationGithubSchemaOwner;
  /** Integration credentials (without value) */
  secret: SecretResponseSchema;
}
