/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * CodeSage API (dev)
 * OpenAPI spec version: 0.1.0
 */
import type { IntegrationResponseIntegration } from "./integrationResponseIntegration";

/**
 * Response containing a single integration.
 */
export interface IntegrationResponse {
  /** Integration data */
  integration: IntegrationResponseIntegration;
}
