/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * CodeSage API (dev)
 * OpenAPI spec version: 0.1.0
 */
import type { SentryIntegrationConfig } from "./sentryIntegrationConfig";
import type { IntegrationSentrySchemaOwner } from "./integrationSentrySchemaOwner";
import type { SecretResponseSchema } from "./secretResponseSchema";

export interface IntegrationSentrySchema {
  created_at: string;
  updated_at: string;
  /** Integration ID */
  id: string;
  /** Integration name */
  name: string;
  /** Provider type (sentry) */
  provider?: "sentry";
  /** Sentry integration configuration */
  config: SentryIntegrationConfig;
  /** Integration owner */
  owner?: IntegrationSentrySchemaOwner;
  /** Integration credentials (without value) */
  secret: SecretResponseSchema;
}
