/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * CodeSage API (dev)
 * OpenAPI spec version: 0.1.0
 */

export interface InterruptResolutionRequest {
  /** Task interrupt identifier */
  interrupt_id: string;
  /** Tool call response */
  response: string;
}
