/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * CodeSage API (dev)
 * OpenAPI spec version: 0.1.0
 */
import type { GitHubIntegrationConfigInput } from "./gitHubIntegrationConfigInput";
import type { SecretRequestSchema } from "./secretRequestSchema";
import type { OwnerRequestSchema } from "./ownerRequestSchema";

export interface IntegrationCreateGitHubSchema {
  /** Integration name */
  name: string;
  /** Provider type (github) */
  provider?: "github";
  /** GitHub integration configuration */
  config: GitHubIntegrationConfigInput;
  /** Integration credentials */
  secret: SecretRequestSchema;
  /** Integration owner */
  owner: OwnerRequestSchema;
}
