/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * CodeSage API (dev)
 * OpenAPI spec version: 0.1.0
 */
import type { NotificationUpdateSchema } from "./notificationUpdateSchema";

export interface NotificationUpdateRequest {
  /** Notification update data */
  notification: NotificationUpdateSchema;
}
