/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * CodeSage API (dev)
 * OpenAPI spec version: 0.1.0
 */

export type OwnerResponseSchemaType =
  (typeof OwnerResponseSchemaType)[keyof typeof OwnerResponseSchemaType];

export const OwnerResponseSchemaType = {
  user: "user",
  group: "group",
} as const;
