/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * CodeSage API (dev)
 * OpenAPI spec version: 0.1.0
 */
import type { OwnerRequestSchemaType } from "./ownerRequestSchemaType";

/**
 * Owner schema for API requests.
 */
export interface OwnerRequestSchema {
  id: number;
  type: OwnerRequestSchemaType;
}
