/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * CodeSage API (dev)
 * OpenAPI spec version: 0.1.0
 */

export type OwnerRequestSchemaType =
  (typeof OwnerRequestSchemaType)[keyof typeof OwnerRequestSchemaType];

export const OwnerRequestSchemaType = {
  user: "user",
  group: "group",
} as const;
