/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * CodeSage API (dev)
 * OpenAPI spec version: 0.1.0
 */

/**
 * Owner name (username or group name)
 */
export type OwnerResponseSchemaName = string | null;
