/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * CodeSage API (dev)
 * OpenAPI spec version: 0.1.0
 */
import type { OwnerResponseSchemaType } from "./ownerResponseSchemaType";

/**
 * Owner schema for API responses.
 */
export interface OwnerResponseSchema {
  id: number;
  type: OwnerResponseSchemaType;
  name: string;
}
