/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * CodeSage API (dev)
 * OpenAPI spec version: 0.1.0
 */

export type ProgrammingLanguage =
  (typeof ProgrammingLanguage)[keyof typeof ProgrammingLanguage];

export const ProgrammingLanguage = {
  cpp: "cpp",
  go: "go",
  java: "java",
  kotlin: "kotlin",
  js: "js",
  ts: "ts",
  php: "php",
  proto: "proto",
  python: "python",
  rst: "rst",
  ruby: "ruby",
  rust: "rust",
  scala: "scala",
  swift: "swift",
  markdown: "markdown",
  latex: "latex",
  html: "html",
  sol: "sol",
  csharp: "csharp",
  cobol: "cobol",
  c: "c",
  lua: "lua",
  perl: "perl",
  haskell: "haskell",
  elixir: "elixir",
  powershell: "powershell",
} as const;
