/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * CodeSage API (dev)
 * OpenAPI spec version: 0.1.0
 */
import type { TaskType } from "./taskType";
import type { TaskState } from "./taskState";
import type { TaskInterrupt } from "./taskInterrupt";
import type { ProjectTaskMessages } from "./projectTaskMessages";

export interface ProjectTask {
  /** Task identifier */
  id: string;
  /** Task type */
  type: TaskType;
  /** Task state */
  state: TaskState;
  /** List of task interrupts */
  interrupts: TaskInterrupt[];
  /** List of messages in the task */
  messages?: ProjectTaskMessages;
}
