/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * CodeSage API (dev)
 * OpenAPI spec version: 0.1.0
 */
import type { ProjectTask } from "./projectTask";

/**
 * List of tasks in the project
 */
export type ProjectRequestTasks = ProjectTask[] | null;
