/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * CodeSage API (dev)
 * OpenAPI spec version: 0.1.0
 */
import type { ProjectCreateSchemaName } from "./projectCreateSchemaName";
import type { ProjectRepositorySchema } from "./projectRepositorySchema";

export interface ProjectCreateSchema {
  /** Project name (optional, autodetected from url) */
  name?: ProjectCreateSchemaName;
  /** Project repository information */
  repository: ProjectRepositorySchema;
}
