/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * CodeSage API (dev)
 * OpenAPI spec version: 0.1.0
 */
import type { ProjectUser } from "./projectUser";

/**
 * List of users in the project
 */
export type ProjectRequestUsers = ProjectUser[] | null;
