/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * CodeSage API (dev)
 * OpenAPI spec version: 0.1.0
 */

export type ProjectRole = typeof ProjectRole[keyof typeof ProjectRole];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ProjectRole = {
  owner: "owner",
  collaborator: "collaborator",
  viewer: "viewer",
} as const;
