/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * CodeSage API (dev)
 * OpenAPI spec version: 0.1.0
 */

/**
 * Project name (optional, autodetected from url)
 */
export type ProjectCreateSchemaName = string | null;
