/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * CodeSage API (dev)
 * OpenAPI spec version: 0.1.0
 */
import type { ProjectRepositoryReference } from "./projectRepositoryReference";
import type { ProjectRepositoryCredentials } from "./projectRepositoryCredentials";

export interface ProjectRepository {
  /**
   * Repository clone URL
   * @minLength 1
   */
  url: string;
  /** Repository reference */
  reference?: ProjectRepositoryReference;
  /** Repository credentials */
  credentials?: ProjectRepositoryCredentials;
}
