/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * CodeSage API (dev)
 * OpenAPI spec version: 0.1.0
 */
import type { ProjectUserSchema } from "./projectUserSchema";
import type { ProjectTaskSchema } from "./projectTaskSchema";
import type { ProjectSchemaRepository } from "./projectSchemaRepository";

export interface ProjectSchema {
  created_at: string;
  updated_at: string;
  /** Project identifier */
  id: string;
  /** Project name */
  name: string;
  /** List of users in the project */
  users: ProjectUserSchema[];
  /** List of tasks in the project */
  tasks: ProjectTaskSchema[];
  /** Project repository information */
  repository?: ProjectSchemaRepository;
}
