/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * CodeSage API (dev)
 * OpenAPI spec version: 0.1.0
 */
import type { TaskResultOutput } from "./taskResultOutput";

/**
 * Task result
 */
export type ProjectTaskOutputResult = TaskResultOutput | null;
