/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * CodeSage API (dev)
 * OpenAPI spec version: 0.1.0
 */
import type { ProjectRole } from "./projectRole";
import type { BaseUserSchema } from "./baseUserSchema";

export interface ProjectUserSchema {
  role: ProjectRole;
  user: BaseUserSchema;
}
