/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * CodeSage API (dev)
 * OpenAPI spec version: 0.1.0
 */
import type { TaskType } from "./taskType";
import type { TaskState } from "./taskState";
import type { TaskInterruptSchema } from "./taskInterruptSchema";
import type { ProjectTaskSchemaMessages } from "./projectTaskSchemaMessages";
import type { ProjectTaskSchemaResult } from "./projectTaskSchemaResult";

export interface ProjectTaskSchema {
  created_at: string;
  updated_at: string;
  /** Task identifier */
  id: string;
  /** Task type */
  type: TaskType;
  /** Task state */
  state: TaskState;
  /** List of task interrupts */
  interrupts: TaskInterruptSchema[];
  /** List of messages in the task */
  messages?: ProjectTaskSchemaMessages;
  /** Task result */
  result?: ProjectTaskSchemaResult;
}
