/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * CodeSage API (dev)
 * OpenAPI spec version: 0.1.0
 */
import type { ProjectRepositorySchemaReference } from "./projectRepositorySchemaReference";
import type { ProjectRepositorySchemaCredentials } from "./projectRepositorySchemaCredentials";

export interface ProjectRepositorySchema {
  /**
   * Repository clone URL
   * @minLength 1
   */
  url: string;
  /** Repository reference */
  reference?: ProjectRepositorySchemaReference;
  /** Repository credentials */
  credentials?: ProjectRepositorySchemaCredentials;
}
