/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * CodeSage API (dev)
 * OpenAPI spec version: 0.1.0
 */
import type { ProjectRepository } from "./projectRepository";
import type { ProjectRequestName } from "./projectRequestName";
import type { ProjectRequestUsers } from "./projectRequestUsers";
import type { ProjectRequestTasks } from "./projectRequestTasks";

export interface ProjectRequest {
  /** Project repository information */
  repository: ProjectRepository;
  /** Project name (optional, autodetected from url) */
  name?: ProjectRequestName;
  /** List of users in the project */
  users?: ProjectRequestUsers;
  /** List of tasks in the project */
  tasks?: ProjectRequestTasks;
}
