/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * CodeSage API (dev)
 * OpenAPI spec version: 0.1.0
 */
import type { ProjectTaskInput } from "./projectTaskInput";

/**
 * List of tasks in the project
 */
export type ProjectRequestTasks = ProjectTaskInput[] | null;
