/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * CodeSage API (dev)
 * OpenAPI spec version: 0.1.0
 */
import type { BaseMessage } from "./baseMessage";

/**
 * List of messages in the task
 */
export type ProjectTaskMessages = BaseMessage[] | null;
