/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * CodeSage API (dev)
 * OpenAPI spec version: 0.1.0
 */
import type { BranchSchema } from "./branchSchema";
import type { TagSchema } from "./tagSchema";
import type { RemoteSchema } from "./remoteSchema";

export interface RepositorySchema {
  name: string;
  active_branch: string;
  branches: BranchSchema[];
  tags: TagSchema[];
  remote: RemoteSchema;
}
