/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * CodeSage API (dev)
 * OpenAPI spec version: 0.1.0
 */
import type { RepoScannerResultSubpath } from "./repoScannerResultSubpath";
import type { ProgrammingLanguage } from "./programmingLanguage";
import type { Dependency } from "./dependency";

export interface RepoScannerResult {
  /** Repository subpath that the scanner result is about. Used if there are multiple projects in the same repository. */
  subpath: RepoScannerResultSubpath;
  /** Project description. */
  description: string;
  /** Programming language name. */
  language: ProgrammingLanguage;
  /** List of tools and linters used in the project repository. Example: [mypy, eslint, prettier, pre-commit] */
  tools: string[];
  /** List of libraries, frameworks and dependencies. Example: [django, fastapi, react, vue] */
  libraries: Dependency[];
  /** Environment in the <language:version> or <runtime:version> format. Example: [python:3.10, node:v16] */
  environment: string;
}
