/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * CodeSage API (dev)
 * OpenAPI spec version: 0.1.0
 */

export type SecretType = (typeof SecretType)[keyof typeof SecretType];

export const SecretType = {
  token: "token",
  credentials: "credentials",
  private_key: "private_key",
} as const;
