/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * CodeSage API (dev)
 * OpenAPI spec version: 0.1.0
 */
import type { TokenSchemaInput } from "./tokenSchemaInput";
import type { CredentialsSchema } from "./credentialsSchema";
import type { PrivateKeySchema } from "./privateKeySchema";

export type SecretRequestSchemaValue =
  | TokenSchemaInput
  | CredentialsSchema
  | PrivateKeySchema;
