/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * CodeSage API (dev)
 * OpenAPI spec version: 0.1.0
 */
import type { SecretType } from "./secretType";

/**
 * Secret configuration for API responses (without sensitive values).
 */
export interface SecretResponseSchema {
  type: SecretType;
}
