/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * CodeSage API (dev)
 * OpenAPI spec version: 0.1.0
 */
import type { SecretType } from "./secretType";
import type { SecretRequestSchemaValue } from "./secretRequestSchemaValue";

/**
 * Secret configuration for API requests.
 */
export interface SecretRequestSchema {
  type: SecretType;
  value: SecretRequestSchemaValue;
}
