/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * CodeSage API (dev)
 * OpenAPI spec version: 0.1.0
 */

export type Severity = typeof Severity[keyof typeof Severity];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const Severity = {
  low: "low",
  medium: "medium",
  high: "high",
  critical: "critical",
} as const;
