/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * CodeSage API (dev)
 * OpenAPI spec version: 0.1.0
 */

export type Status = typeof Status[keyof typeof Status];

export const Status = {
  success: "success",
  error: "error",
  queued: "queued",
} as const;
