/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * CodeSage API (dev)
 * OpenAPI spec version: 0.1.0
 */
import type { SupervisorResultInputSubpath } from "./supervisorResultInputSubpath";
import type { RepoScannerResult } from "./repoScannerResult";
import type { ToolAnalysisResultInput } from "./toolAnalysisResultInput";

export interface SupervisorResultInput {
  /** Repository subpath that the result is about. Used if there are multiple projects in the same repository. */
  subpath: SupervisorResultInputSubpath;
  /** RepoScannerAgent result for the current subpath or the whole repository if no subprojects were detected. */
  scanner_result: RepoScannerResult;
  /** ToolAnalysisAgent result for the current subpath or the whole repository if no subprojects were detected. */
  tool_analysis_result: ToolAnalysisResultInput;
}
