/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * CodeSage API (dev)
 * OpenAPI spec version: 0.1.0
 */
import type { SupervisorResultOutputSubpath } from "./supervisorResultOutputSubpath";
import type { RepoScannerResult } from "./repoScannerResult";
import type { ToolAnalysisResultOutput } from "./toolAnalysisResultOutput";

export interface SupervisorResultOutput {
  /** Repository subpath that the result is about. Used if there are multiple projects in the same repository. */
  subpath: SupervisorResultOutputSubpath;
  /** RepoScannerAgent result for the current subpath or the whole repository if no subprojects were detected. */
  scanner_result: RepoScannerResult;
  /** ToolAnalysisAgent result for the current subpath or the whole repository if no subprojects were detected. */
  tool_analysis_result: ToolAnalysisResultOutput;
}
