/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * CodeSage API (dev)
 * OpenAPI spec version: 0.1.0
 */
import type { TagSchemaMessage } from "./tagSchemaMessage";
import type { TagSchemaAuthor } from "./tagSchemaAuthor";
import type { TagSchemaTaggedAt } from "./tagSchemaTaggedAt";

export interface TagSchema {
  id: string;
  name: string;
  commit_sha: string;
  message?: TagSchemaMessage;
  author?: TagSchemaAuthor;
  tagged_at?: TagSchemaTaggedAt;
}
