/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * CodeSage API (dev)
 * OpenAPI spec version: 0.1.0
 */
import type { ProjectTask } from "./projectTask";

export interface TasksResponse {
  /** List of tasks */
  tasks: ProjectTask[];
}
