/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * CodeSage API (dev)
 * OpenAPI spec version: 0.1.0
 */

export interface TaskInterrupt {
  /** Task interrupt identifier */
  id: string;
  /** Agent name */
  agent: string;
  /** Text of the interrupt */
  text: string;
  /** Is the interrupt pending */
  pending: boolean;
}
