/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * CodeSage API (dev)
 * OpenAPI spec version: 0.1.0
 */
import type { SupervisorResultsInput } from "./supervisorResultsInput";
import type { RepoScannerResultsInput } from "./repoScannerResultsInput";
import type { ToolAnalysisResultInput } from "./toolAnalysisResultInput";

/**
 * Task result data
 */
export type TaskResultInputResult =
  | SupervisorResultsInput
  | RepoScannerResultsInput
  | ToolAnalysisResultInput;
