/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * CodeSage API (dev)
 * OpenAPI spec version: 0.1.0
 */

export type TaskState = (typeof TaskState)[keyof typeof TaskState];

export const TaskState = {
  pending: "pending",
  running: "running",
  completed: "completed",
  failed: "failed",
  interrupted: "interrupted",
  timeout: "timeout",
  cancelled: "cancelled",
  waiting: "waiting",
} as const;
