/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * CodeSage API (dev)
 * OpenAPI spec version: 0.1.0
 */
import type { SupervisorResultsOutput } from "./supervisorResultsOutput";
import type { RepoScannerResultsOutput } from "./repoScannerResultsOutput";
import type { ToolAnalysisResultOutput } from "./toolAnalysisResultOutput";

/**
 * Task result data
 */
export type TaskResultOutputResult =
  | SupervisorResultsOutput
  | RepoScannerResultsOutput
  | ToolAnalysisResultOutput;
