/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * CodeSage API (dev)
 * OpenAPI spec version: 0.1.0
 */

export type TaskType = typeof TaskType[keyof typeof TaskType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const TaskType = {
  initial_scan: "initial_scan",
  chat: "chat",
} as const;
