/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * CodeSage API (dev)
 * OpenAPI spec version: 0.1.0
 */
import type { RepoScannerResults } from "./repoScannerResults";
import type { InitialScanSupervisorResults } from "./initialScanSupervisorResults";
import type { ToolAnalysisResults } from "./toolAnalysisResults";
import type { EnvironmentSetupResults } from "./environmentSetupResults";

/**
 * Task result data
 */
export type TaskResultSchemaResult =
  | RepoScannerResults
  | InitialScanSupervisorResults
  | ToolAnalysisResults
  | EnvironmentSetupResults;
