/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * CodeSage API (dev)
 * OpenAPI spec version: 0.1.0
 */
import type { TaskResultOutputResult } from "./taskResultOutputResult";

export interface TaskResultOutput {
  /** Task result identifier */
  id: string;
  /** Result model type */
  type: string;
  /** Task result data */
  result: TaskResultOutputResult;
}
