/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * CodeSage API (dev)
 * OpenAPI spec version: 0.1.0
 */
import type { TaskResultInputResult } from "./taskResultInputResult";

export interface TaskResultInput {
  /** Task result identifier */
  id: string;
  /** Result model type */
  type: string;
  /** Task result data */
  result: TaskResultInputResult;
}
