/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * CodeSage API (dev)
 * OpenAPI spec version: 0.1.0
 */

export interface Token {
  refresh_token: string;
  access_token: string;
  token_type: string;
}
