/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * CodeSage API (dev)
 * OpenAPI spec version: 0.1.0
 */
import type { Severity } from "./severity";
import type { CodePoint } from "./codePoint";

export interface ToolAnalysisOutput {
  /** Name of the tool or linter that provided this output. */
  tool: string;
  /** Name of the tool or linter that provided this output. */
  severity: Severity;
  /** Tool message description. */
  description: string;
  /** File location of the detected issue. */
  code_point: CodePoint;
}
