/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * CodeSage API (dev)
 * OpenAPI spec version: 0.1.0
 */
import type { ToolAnalysisResultInputSubpath } from "./toolAnalysisResultInputSubpath";
import type { ToolAnalysisOutput } from "./toolAnalysisOutput";

export interface ToolAnalysisResultInput {
  /** Repository subpath that the results are about. Used if there are multiple projects in the same repository. */
  subpath: ToolAnalysisResultInputSubpath;
  results: ToolAnalysisOutput[];
}
