/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * CodeSage API (dev)
 * OpenAPI spec version: 0.1.0
 */
import type { UserUpdateEmail } from "./userUpdateEmail";
import type { UserUpdateFirstName } from "./userUpdateFirstName";
import type { UserUpdateLastName } from "./userUpdateLastName";
import type { UserUpdatePassword } from "./userUpdatePassword";

export interface UserUpdate {
  /** User email */
  email?: UserUpdateEmail;
  /** User first name */
  first_name?: UserUpdateFirstName;
  /** User last name */
  last_name?: UserUpdateLastName;
  /** Password update details */
  password?: UserUpdatePassword;
}
