/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * CodeSage API (dev)
 * OpenAPI spec version: 0.1.0
 */
import type { UserNotificationSchemaReadAt } from "./userNotificationSchemaReadAt";
import type { UserNotificationSchemaLink } from "./userNotificationSchemaLink";

export interface UserNotificationSchema {
  /** Notification identifier */
  id: string;
  /** Notification type */
  notification_type: string;
  /** Notification text */
  text: string;
  /** Read date */
  read_at?: UserNotificationSchemaReadAt;
  /** Notification link */
  link?: UserNotificationSchemaLink;
}
