/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * CodeSage API (dev)
 * OpenAPI spec version: 0.1.0
 */
import type { UserGroupSchema } from "./userGroupSchema";

/**
 * User groups
 */
export type UserSchemaGroups = UserGroupSchema[] | null;
