/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * CodeSage API (dev)
 * OpenAPI spec version: 0.1.0
 */
import type { UserUpdateSchemaEmail } from "./userUpdateSchemaEmail";
import type { UserUpdateSchemaFirstName } from "./userUpdateSchemaFirstName";
import type { UserUpdateSchemaLastName } from "./userUpdateSchemaLastName";
import type { UserUpdateSchemaPassword } from "./userUpdateSchemaPassword";

export interface UserUpdateSchema {
  /** User email */
  email?: UserUpdateSchemaEmail;
  /** User first name */
  first_name?: UserUpdateSchemaFirstName;
  /** User last name */
  last_name?: UserUpdateSchemaLastName;
  /** Password update details */
  password?: UserUpdateSchemaPassword;
}
