/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * CodeSage API (dev)
 * OpenAPI spec version: 0.1.0
 */
import type { UserFirstName } from "./userFirstName";
import type { UserLastName } from "./userLastName";

export interface User {
  /** User identifier */
  id: number;
  /** User name */
  username: string;
  /** User email */
  email: string;
  /** User first name */
  first_name?: UserFirstName;
  /** User last name */
  last_name?: UserLastName;
  /** User creation date */
  date_joined: string;
}
