/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * CodeSage API (dev)
 * OpenAPI spec version: 0.1.0
 */
import type { UserSchemaEmail } from "./userSchemaEmail";
import type { UserSchemaFirstName } from "./userSchemaFirstName";
import type { UserSchemaLastName } from "./userSchemaLastName";
import type { UserSchemaNotifications } from "./userSchemaNotifications";
import type { UserSchemaGroups } from "./userSchemaGroups";

export interface UserSchema {
  /** User identifier */
  id: number;
  /** User name */
  username: string;
  /** User email */
  email?: UserSchemaEmail;
  /** User first name */
  first_name?: UserSchemaFirstName;
  /** User last name */
  last_name?: UserSchemaLastName;
  /** User creation date */
  date_joined: string;
  /** User notifications */
  notifications?: UserSchemaNotifications;
  /** User groups */
  groups?: UserSchemaGroups;
}
