/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * CodeSage API (dev)
 * OpenAPI spec version: 0.1.0
 */
import { useMutation, useQuery } from "@tanstack/react-query";
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from "@tanstack/react-query";

import * as axios from "axios";
import type { AxiosError, AxiosRequestConfig, AxiosResponse } from "axios";

import type {
  BaseErrorResponse,
  HTTPValidationError,
  IntegrationsResponse,
  MultipleErrorResponse,
  NotificationUpdateRequest,
  ProjectsResponse,
  UserResponse,
  UserUpdateRequest,
} from "../../models";

/**
 * Get user information.
 * @summary Get User Info
 */
export const getUserInfo = (
  userId: number | "me",
  options?: AxiosRequestConfig,
): Promise<AxiosResponse<UserResponse>> => {
  return axios.default.get(`/api/users/${userId}`, options);
};

export const getGetUserInfoQueryKey = (userId: number | "me") => {
  return [`/api/users/${userId}`] as const;
};

export const getGetUserInfoQueryOptions = <
  TData = Awaited<ReturnType<typeof getUserInfo>>,
  TError = AxiosError<BaseErrorResponse | HTTPValidationError>,
>(
  userId: number | "me",
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getUserInfo>>, TError, TData>
    >;
    axios?: AxiosRequestConfig;
  },
) => {
  const { query: queryOptions, axios: axiosOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetUserInfoQueryKey(userId);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getUserInfo>>> = ({
    signal,
  }) => getUserInfo(userId, { signal, ...axiosOptions });

  return {
    queryKey,
    queryFn,
    enabled: !!userId,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof getUserInfo>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetUserInfoQueryResult = NonNullable<
  Awaited<ReturnType<typeof getUserInfo>>
>;
export type GetUserInfoQueryError = AxiosError<
  BaseErrorResponse | HTTPValidationError
>;

export function useGetUserInfo<
  TData = Awaited<ReturnType<typeof getUserInfo>>,
  TError = AxiosError<BaseErrorResponse | HTTPValidationError>,
>(
  userId: number | "me",
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getUserInfo>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getUserInfo>>,
          TError,
          Awaited<ReturnType<typeof getUserInfo>>
        >,
        "initialData"
      >;
    axios?: AxiosRequestConfig;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetUserInfo<
  TData = Awaited<ReturnType<typeof getUserInfo>>,
  TError = AxiosError<BaseErrorResponse | HTTPValidationError>,
>(
  userId: number | "me",
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getUserInfo>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getUserInfo>>,
          TError,
          Awaited<ReturnType<typeof getUserInfo>>
        >,
        "initialData"
      >;
    axios?: AxiosRequestConfig;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetUserInfo<
  TData = Awaited<ReturnType<typeof getUserInfo>>,
  TError = AxiosError<BaseErrorResponse | HTTPValidationError>,
>(
  userId: number | "me",
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getUserInfo>>, TError, TData>
    >;
    axios?: AxiosRequestConfig;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Get User Info
 */

export function useGetUserInfo<
  TData = Awaited<ReturnType<typeof getUserInfo>>,
  TError = AxiosError<BaseErrorResponse | HTTPValidationError>,
>(
  userId: number | "me",
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getUserInfo>>, TError, TData>
    >;
    axios?: AxiosRequestConfig;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetUserInfoQueryOptions(userId, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * Update user information.
 * @summary Update User Info
 */
export const updateUserInfo = (
  userId: number | "me",
  userUpdateRequest: UserUpdateRequest,
  options?: AxiosRequestConfig,
): Promise<AxiosResponse<UserResponse>> => {
  return axios.default.patch(
    `/api/users/${userId}`,
    userUpdateRequest,
    options,
  );
};

export const getUpdateUserInfoMutationOptions = <
  TError = AxiosError<
    MultipleErrorResponse | BaseErrorResponse | HTTPValidationError
  >,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof updateUserInfo>>,
    TError,
    { userId: number | "me"; data: UserUpdateRequest },
    TContext
  >;
  axios?: AxiosRequestConfig;
}): UseMutationOptions<
  Awaited<ReturnType<typeof updateUserInfo>>,
  TError,
  { userId: number | "me"; data: UserUpdateRequest },
  TContext
> => {
  const mutationKey = ["updateUserInfo"];
  const { mutation: mutationOptions, axios: axiosOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, axios: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof updateUserInfo>>,
    { userId: number | "me"; data: UserUpdateRequest }
  > = (props) => {
    const { userId, data } = props ?? {};

    return updateUserInfo(userId, data, axiosOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type UpdateUserInfoMutationResult = NonNullable<
  Awaited<ReturnType<typeof updateUserInfo>>
>;
export type UpdateUserInfoMutationBody = UserUpdateRequest;
export type UpdateUserInfoMutationError = AxiosError<
  MultipleErrorResponse | BaseErrorResponse | HTTPValidationError
>;

/**
 * @summary Update User Info
 */
export const useUpdateUserInfo = <
  TError = AxiosError<
    MultipleErrorResponse | BaseErrorResponse | HTTPValidationError
  >,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof updateUserInfo>>,
      TError,
      { userId: number | "me"; data: UserUpdateRequest },
      TContext
    >;
    axios?: AxiosRequestConfig;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof updateUserInfo>>,
  TError,
  { userId: number | "me"; data: UserUpdateRequest },
  TContext
> => {
  const mutationOptions = getUpdateUserInfoMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * Get projects for a user.
 * @summary Get Projects
 */
export const getProjects = (
  userId: number | "me",
  options?: AxiosRequestConfig,
): Promise<AxiosResponse<ProjectsResponse>> => {
  return axios.default.get(`/api/users/${userId}/projects`, options);
};

export const getGetProjectsQueryKey = (userId: number | "me") => {
  return [`/api/users/${userId}/projects`] as const;
};

export const getGetProjectsQueryOptions = <
  TData = Awaited<ReturnType<typeof getProjects>>,
  TError = AxiosError<BaseErrorResponse | HTTPValidationError>,
>(
  userId: number | "me",
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getProjects>>, TError, TData>
    >;
    axios?: AxiosRequestConfig;
  },
) => {
  const { query: queryOptions, axios: axiosOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetProjectsQueryKey(userId);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getProjects>>> = ({
    signal,
  }) => getProjects(userId, { signal, ...axiosOptions });

  return {
    queryKey,
    queryFn,
    enabled: !!userId,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof getProjects>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetProjectsQueryResult = NonNullable<
  Awaited<ReturnType<typeof getProjects>>
>;
export type GetProjectsQueryError = AxiosError<
  BaseErrorResponse | HTTPValidationError
>;

export function useGetProjects<
  TData = Awaited<ReturnType<typeof getProjects>>,
  TError = AxiosError<BaseErrorResponse | HTTPValidationError>,
>(
  userId: number | "me",
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getProjects>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getProjects>>,
          TError,
          Awaited<ReturnType<typeof getProjects>>
        >,
        "initialData"
      >;
    axios?: AxiosRequestConfig;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetProjects<
  TData = Awaited<ReturnType<typeof getProjects>>,
  TError = AxiosError<BaseErrorResponse | HTTPValidationError>,
>(
  userId: number | "me",
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getProjects>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getProjects>>,
          TError,
          Awaited<ReturnType<typeof getProjects>>
        >,
        "initialData"
      >;
    axios?: AxiosRequestConfig;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetProjects<
  TData = Awaited<ReturnType<typeof getProjects>>,
  TError = AxiosError<BaseErrorResponse | HTTPValidationError>,
>(
  userId: number | "me",
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getProjects>>, TError, TData>
    >;
    axios?: AxiosRequestConfig;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Get Projects
 */

export function useGetProjects<
  TData = Awaited<ReturnType<typeof getProjects>>,
  TError = AxiosError<BaseErrorResponse | HTTPValidationError>,
>(
  userId: number | "me",
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof getProjects>>, TError, TData>
    >;
    axios?: AxiosRequestConfig;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetProjectsQueryOptions(userId, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}

/**
 * Get projects for a user.
 * @summary Update Notification
 */
export const updateNotification = (
  userId: number | "me",
  notificationId: string,
  notificationUpdateRequest: NotificationUpdateRequest,
  options?: AxiosRequestConfig,
): Promise<AxiosResponse<UserResponse>> => {
  return axios.default.patch(
    `/api/users/${userId}/notifications/${notificationId}`,
    notificationUpdateRequest,
    options,
  );
};

export const getUpdateNotificationMutationOptions = <
  TError = AxiosError<BaseErrorResponse | HTTPValidationError>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof updateNotification>>,
    TError,
    {
      userId: number | "me";
      notificationId: string;
      data: NotificationUpdateRequest;
    },
    TContext
  >;
  axios?: AxiosRequestConfig;
}): UseMutationOptions<
  Awaited<ReturnType<typeof updateNotification>>,
  TError,
  {
    userId: number | "me";
    notificationId: string;
    data: NotificationUpdateRequest;
  },
  TContext
> => {
  const mutationKey = ["updateNotification"];
  const { mutation: mutationOptions, axios: axiosOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, axios: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof updateNotification>>,
    {
      userId: number | "me";
      notificationId: string;
      data: NotificationUpdateRequest;
    }
  > = (props) => {
    const { userId, notificationId, data } = props ?? {};

    return updateNotification(userId, notificationId, data, axiosOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type UpdateNotificationMutationResult = NonNullable<
  Awaited<ReturnType<typeof updateNotification>>
>;
export type UpdateNotificationMutationBody = NotificationUpdateRequest;
export type UpdateNotificationMutationError = AxiosError<
  BaseErrorResponse | HTTPValidationError
>;

/**
 * @summary Update Notification
 */
export const useUpdateNotification = <
  TError = AxiosError<BaseErrorResponse | HTTPValidationError>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof updateNotification>>,
      TError,
      {
        userId: number | "me";
        notificationId: string;
        data: NotificationUpdateRequest;
      },
      TContext
    >;
    axios?: AxiosRequestConfig;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof updateNotification>>,
  TError,
  {
    userId: number | "me";
    notificationId: string;
    data: NotificationUpdateRequest;
  },
  TContext
> => {
  const mutationOptions = getUpdateNotificationMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
/**
 * Get integrations for a user.
 * @summary Get Integrations
 */
export const getIntegrations = (
  userId: number | "me",
  options?: AxiosRequestConfig,
): Promise<AxiosResponse<IntegrationsResponse>> => {
  return axios.default.get(`/api/users/${userId}/integrations`, options);
};

export const getGetIntegrationsQueryKey = (userId: number | "me") => {
  return [`/api/users/${userId}/integrations`] as const;
};

export const getGetIntegrationsQueryOptions = <
  TData = Awaited<ReturnType<typeof getIntegrations>>,
  TError = AxiosError<BaseErrorResponse | HTTPValidationError>,
>(
  userId: number | "me",
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getIntegrations>>,
        TError,
        TData
      >
    >;
    axios?: AxiosRequestConfig;
  },
) => {
  const { query: queryOptions, axios: axiosOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetIntegrationsQueryKey(userId);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getIntegrations>>> = ({
    signal,
  }) => getIntegrations(userId, { signal, ...axiosOptions });

  return {
    queryKey,
    queryFn,
    enabled: !!userId,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof getIntegrations>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetIntegrationsQueryResult = NonNullable<
  Awaited<ReturnType<typeof getIntegrations>>
>;
export type GetIntegrationsQueryError = AxiosError<
  BaseErrorResponse | HTTPValidationError
>;

export function useGetIntegrations<
  TData = Awaited<ReturnType<typeof getIntegrations>>,
  TError = AxiosError<BaseErrorResponse | HTTPValidationError>,
>(
  userId: number | "me",
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getIntegrations>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getIntegrations>>,
          TError,
          Awaited<ReturnType<typeof getIntegrations>>
        >,
        "initialData"
      >;
    axios?: AxiosRequestConfig;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetIntegrations<
  TData = Awaited<ReturnType<typeof getIntegrations>>,
  TError = AxiosError<BaseErrorResponse | HTTPValidationError>,
>(
  userId: number | "me",
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getIntegrations>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getIntegrations>>,
          TError,
          Awaited<ReturnType<typeof getIntegrations>>
        >,
        "initialData"
      >;
    axios?: AxiosRequestConfig;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetIntegrations<
  TData = Awaited<ReturnType<typeof getIntegrations>>,
  TError = AxiosError<BaseErrorResponse | HTTPValidationError>,
>(
  userId: number | "me",
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getIntegrations>>,
        TError,
        TData
      >
    >;
    axios?: AxiosRequestConfig;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary Get Integrations
 */

export function useGetIntegrations<
  TData = Awaited<ReturnType<typeof getIntegrations>>,
  TError = AxiosError<BaseErrorResponse | HTTPValidationError>,
>(
  userId: number | "me",
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof getIntegrations>>,
        TError,
        TData
      >
    >;
    axios?: AxiosRequestConfig;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getGetIntegrationsQueryOptions(userId, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey;

  return query;
}
