/**
 * Generated by orval v7.9.0 🍺
 * Do not edit manually.
 * CodeSage API (dev)
 * OpenAPI spec version: 0.1.0
 */
import { useMutation } from "@tanstack/react-query";
import type {
  MutationFunction,
  QueryClient,
  UseMutationOptions,
  UseMutationResult,
} from "@tanstack/react-query";

import * as axios from "axios";
import type { AxiosError, AxiosRequestConfig, AxiosResponse } from "axios";

import type {
  BaseErrorResponse,
  BodyLoginApiTokenPost,
  HTTPValidationError,
  TokenSchemaOutput,
} from "../../models";

/**
 * @summary Login
 */
export const login = (
  bodyLoginApiTokenPost: BodyLoginApiTokenPost,
  options?: AxiosRequestConfig,
): Promise<AxiosResponse<TokenSchemaOutput>> => {
  const formUrlEncoded = new URLSearchParams();
  if (
    bodyLoginApiTokenPost.grant_type !== undefined &&
    bodyLoginApiTokenPost.grant_type !== null
  ) {
    formUrlEncoded.append(`grant_type`, bodyLoginApiTokenPost.grant_type);
  }
  if (
    bodyLoginApiTokenPost.refresh_token !== undefined &&
    bodyLoginApiTokenPost.refresh_token !== null
  ) {
    formUrlEncoded.append(`refresh_token`, bodyLoginApiTokenPost.refresh_token);
  }
  if (
    bodyLoginApiTokenPost.username !== undefined &&
    bodyLoginApiTokenPost.username !== null
  ) {
    formUrlEncoded.append(`username`, bodyLoginApiTokenPost.username);
  }
  if (
    bodyLoginApiTokenPost.password !== undefined &&
    bodyLoginApiTokenPost.password !== null
  ) {
    formUrlEncoded.append(`password`, bodyLoginApiTokenPost.password);
  }
  if (bodyLoginApiTokenPost.scope !== undefined) {
    formUrlEncoded.append(`scope`, bodyLoginApiTokenPost.scope);
  }
  if (
    bodyLoginApiTokenPost.client_id !== undefined &&
    bodyLoginApiTokenPost.client_id !== null
  ) {
    formUrlEncoded.append(`client_id`, bodyLoginApiTokenPost.client_id);
  }
  if (
    bodyLoginApiTokenPost.client_secret !== undefined &&
    bodyLoginApiTokenPost.client_secret !== null
  ) {
    formUrlEncoded.append(`client_secret`, bodyLoginApiTokenPost.client_secret);
  }

  return axios.default.post(`/api/token`, formUrlEncoded, options);
};

export const getLoginMutationOptions = <
  TError = AxiosError<BaseErrorResponse | HTTPValidationError>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof login>>,
    TError,
    { data: BodyLoginApiTokenPost },
    TContext
  >;
  axios?: AxiosRequestConfig;
}): UseMutationOptions<
  Awaited<ReturnType<typeof login>>,
  TError,
  { data: BodyLoginApiTokenPost },
  TContext
> => {
  const mutationKey = ["login"];
  const { mutation: mutationOptions, axios: axiosOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, axios: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof login>>,
    { data: BodyLoginApiTokenPost }
  > = (props) => {
    const { data } = props ?? {};

    return login(data, axiosOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type LoginMutationResult = NonNullable<
  Awaited<ReturnType<typeof login>>
>;
export type LoginMutationBody = BodyLoginApiTokenPost;
export type LoginMutationError = AxiosError<
  BaseErrorResponse | HTTPValidationError
>;

/**
 * @summary Login
 */
export const useLogin = <
  TError = AxiosError<BaseErrorResponse | HTTPValidationError>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof login>>,
      TError,
      { data: BodyLoginApiTokenPost },
      TContext
    >;
    axios?: AxiosRequestConfig;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof login>>,
  TError,
  { data: BodyLoginApiTokenPost },
  TContext
> => {
  const mutationOptions = getLoginMutationOptions(options);

  return useMutation(mutationOptions, queryClient);
};
